### PR TITLE
[Resolve Errors] [Review Warnings] Exceed error warning limit alert & counts read off the response body

### LINKED ISSUE #623: [Resolve Errors] [Review Warnings] Exceed error/warning limit - Provide a notice and a download report link in the FieldEntry
- follow the figma example in the errors page
Screenshot 2024-06-03 at 1 15 59 PM
Screenshot 2024-06-03 at 2 55 46 PM

### LINKED ISSUE #624: [Resolve Errors] [Review Warnings] Exceed error/warning limit - Use backend provided counts (single/multi/register)

### LINKED ISSUE #630: [Resolve Errors] [Review Warnings] Exceed error/warning limit - detect property in indicating additional errors
Based on the `is_truncated` flag.

### LINKED ISSUE #704: [Resolve Errors] [Review Warnings] Download Validation Report Link: Scroll to the Download Validation Report button

### PR DESCRIPTION
**Pull request by shindigira**
closes #623
closes #624 
closes #630 
closes #704 

## Changes
- feat(Errors/Warnings): A field alert alert appears when the error/warnings limit is exceeded (i.e. `is_truncated`)
- feat(Errors/Warnings): Single Field, Multi Field and Register counts now come from the data response object
- enhancement(Download Validation Report): Added button loader
- enhancement(Field Level Alert - Download Validation Report Link): Now scrolls to the Download Validation Report button

## How to Test
- Upload [1_000_000 errors](https://github.com/cfpb/sbl-test-data/blob/main/locust-sblars/100000_entries_findings.csv)
- Navigate to Errors and/or Warnings 
- Ensure the counts properly match the data response object
- The Field Level Alert appears when necessary
- Test the Download Validation report link 

## Screenshot
Screenshot 2024-06-12 at 2 50 47 PM
Screenshot 2024-06-12 at 2 50 47 PM
Screenshot 2024-06-12 at 2 50 47 PM

### CODE REVIEW

**Review by meissadia — CHANGES_REQUESTED** [review]
Not working for me.  I am seeing zeroes in the UI for error counts when there are `400` logic errors shown in `/submission/latest` response, as well as errors shown in tables. 
 
I *think* the `Download Report` function is working well.  Downloaded report shows 200,727 entries - I'm not sure what source I could compare that against to determine if that is the correct number of triggered validations.

## API response
Screenshot 2024-06-12 at 4 46 08 PM

## UI
screencapture-localhost-8899-filing-2024-123456789MEISBANK808-errors-2024-06-12-16_45_40

**Review by meissadia — CHANGES_REQUESTED** [review]
@shindigira Sorry for that oversight and thanks for the clarification, I've updated my backend

- The numbers displayed in the UI seem to match what I'm seeing in the API. 👍🏾 
- Download report looks good 👍🏾 
- I do see one `upload a new file` link missing form the error Alert box
  - Screenshot 2024-06-13 at 12 54 12 PM

**Review by meissadia — APPROVED** [review]
LGTM! 👍🏾

**Comment by natalia-fitzgerald** [comment]
@shindigira 
Please see related feedback posted here: https://github.com/cfpb/sbl-frontend/issues/578
Screenshot 2024-06-17 at 9 47 13 PM
Screenshot 2024-06-17 at 9 47 19 PM

**Comment by billhimmelsbach** [comment]
I don't think you had the chance to merge this great PR in before ya left, so going to do that now just [to avoid some conflicts ](https://github.com/cfpb/sbl-frontend/pull/724#pullrequestreview-2126735035)with related PRs.

**Pull request merged**
