### PR TITLE
[DRAFT] feat(deps): update to node 18, yarn 4

### PR DESCRIPTION
**Pull request by billhimmelsbach**
Found this bug when trying to run tests locally:

Screenshot 2024-04-27 at 4 43 24 PM

This bug is [caused by](https://github.com/yarnpkg/berry/pull/6030) running on an old version of node on older versions of yarn when using vitest, which has [been fixed in later updates](https://github.com/yarnpkg/berry/pull/6030). Updating to the latest version of yarn fixes this issue (the [DS did it earlier this year](https://github.com/cfpb/design-system/commit/2691a16d1ec50bf9dcac6aca63fab19573742f1f)), but v4 of yarn also requires at least node 18. We should at least update from node 16 to node 18 anyway for the engine, [since it's at EOL](https://github.com/nodejs/Release). We could also update all the way to node 20, or even 22 if we're ok with it not being a LTS release for a few months. We can probably wait till post-mvp for that change.

## Changes
- update yarn to v4
- update node to 18, maybe even 20/22 post-mvp if we're ok not being on a LTS release for a few months

## How to test this PR

- make sure you're using node 18, if you're using nvm, it's `nvm use 18`
- make sure you're using the prescribed version of yarn, it's `yarn set version 4.1.1` or use corepack
- does vite still build things correctly? `yarn run dev`
- can you run your tests locally? `yarn test`

### Before

Screenshot 2024-04-27 at 4 43 24 PM

### After
Screenshot 2024-04-28 at 9 34 36 AM

### CODE REVIEW

**Comment by billhimmelsbach** [comment]
Confirmed there's no node version stated in the DDD, so we're good to go for a review for this one @shindigira and @meissadia 👍

**Review by meissadia — APPROVED** [review]
Tests run successfully 👌🏾 
 
I was trying to update `.nvmrc` but accidentally pushed the commit to branch `418-bump-deps-for-security-audit` instead of this one 😞

**Comment by billhimmelsbach** [comment]
> Tests run successfully 👌🏾
> 
> I was trying to update `.nvmrc` but accidentally pushed the commit to branch `418-bump-deps-for-security-audit` instead of this one 😞

Good catch though on the `.nvmrc` file [over here](https://github.com/cfpb/sbl-frontend/pull/419/commits/500872e7d5511997a9b33cf723436bb5b2baf65f). I'll merge this one, and then we can incorporate that change in that other PR?

**Comment by billhimmelsbach** [comment]
Ok, I went ahead and put the nvmrc commit over here, so good to go! 👍

**Pull request merged**
