### PR TITLE
fix: 404/500 Language update v1

### LINKED ISSUE #178: [Content Review] SBL "404 - Not found" & "500 - Error pages"
These pages are clones of pages shown on CF.gov. 
 
We are looking for feedback on if the page language still fits within the context of the SBL app. 
 
✅  The 500 page clearly needs some rewording. I will take a crack at that tomorrow (1/18).

Length restrictions:
  - Don't go past 2 lines of text @ desktop width

## 404 - Not found
Screenshot 2024-01-19 at 3 39 37 PM

## 500 - Error
Screenshot 2024-01-19 at 3 41 24 PM

### PR DESCRIPTION
**Pull request by meissadia**
Closes #178 

Screenshots updated 1/23

## 404 - Not found
Screenshot 2024-01-23 at 11 07 03 AM

## 500 - Error
Screenshot 2024-01-23 at 11 07 20 AM

### CODE REVIEW

**Comment by billhimmelsbach** [comment]
@meissadia Did this get a Natalia review yet? Is this good to go?

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@meissadia 
The max width for the text content should be 670px. It looks like we are exceeding that max width in this implementation. Can we adjust that?

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach @meissadia @dan-padgett 
Did we nail down where a user will go if they click on the "Visit platform home"? Will it depend on whether they hit this page after successfully logging in and completed their user profile or not? The questions we added before the contact support link are meant to be read as, if the answer to this question is true then contact our support staff? "Has this error persisted" is meant to ask whether they have tried multiple times and had the same result?

**Comment by billhimmelsbach** [comment]
> Did we nail down where a user will go if they click on the "Visit platform home"? 

We should send them to the unauthenticated landing page because it's least likely to lead immediately to another 500. If we ever needed to put up a "System is down/Maintenance" message post-mvp, it would also go there on the unauthenticated landing page which also makes me want to direct people to it if they encounter errors.

> "Has this error persisted" 
I feel like a more plain language explanation might be good, maybe something like: "Does this error keep happening?"

**Comment by meissadia** [comment]
@natalia-fitzgerald @billhimmelsbach 

Updated language and widths:

404-updated


Screenshot 2024-01-30 at 1 01 42 PM

**Review by natalia-fitzgerald — APPROVED** [review]
Looks good @meissadia!

**Pull request merged**
