### PR TITLE
[Loading] Use generic "Loading" message for all statuses

### LINKED ISSUE #769: [Loading] Simplify messages; Adjust positioning

### PR DESCRIPTION
**Pull request by meissadia**
Close #769 

## Changes
- Display LoadingContent text as H3
- I searched for all instances of "loading", "updating", or "saving" and replaced any detailed status messaging with a plain "Loading"

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Did we also fix the exclamation point in the error message that I flagged?

**Comment by meissadia** [comment]
> @meissadia Did we also fix the exclamation point in the error message that I flagged?

@natalia-fitzgerald Yes
 
https://github.com/cfpb/sbl-frontend/pull/774/files#diff-a172a52e6954972ee06208c37fe8fd13c1d62619ac2be3f623cdb3af4ba1f557R184

**Review by billhimmelsbach — APPROVED** [review]
RIP Ellipsis 🪦 ... 🫡

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach - Has this gone live on the platform? I'm not sure how to track it down to check it but I see the change here and see that it has been merged. Should that be enough for me to check this item off of my list?

**Pull request merged**
