### PR TITLE
[Update Institution Profile] Form validations

### PR DESCRIPTION
**Pull request by meissadia**
Phase 4 of #222 

## Changes
- Eliminates the majority of ESLint exception previously applied in the UpdateFinancialProfile folder
- Updates type structures used to manage the UFP form
- Validates TIN
- Validates RSSD ID
- Ensures at least one Type of financial institution is selected
- Ensures that if Type - `Other` is selected, a description is entered in the checkbox
- Clears the description textbox and disables it if Type - `Other` is deselected
- Ensures *some* Institution data has been modified before allowing the user to submit the form
  - Note: Disabling the `Submit` button requires more extensive modifications due to struggles I've had getting `react-hook-form` to recognize changes to the `Type of financial institution` and `Additional details` fields.

## Questions
- [x] Are current error messages sufficient? 
  - ~~Particularly for RSSD ID: `Expected number, received nan`~~
  - Updated to: `RSSD ID must be a number`
- [x] What validations are needed for `Top Holder` and `Parent Entity`
  - ex. If LEI/RSSDID are populated, does Name have to be populated? (not implemented)
  - Update: No additional validations for now
- [x] Can a user submit the form with only `Additional details` populated?
  - Currently we block that
  - Update: Will continue to block for now.  Need to determine if this `Update` form should be allowed for other purposes

## How to test this PR

1. Visit http://localhost:8899/institution/123456789TESTBANK123/update
2. Click `Submit` without making any changes, you'll see a warning
3. Change TIN to an invalid entry i.e. `88-912312` and hit `Submit`, see that you get an error
4. Delete content in RSSD ID and hit `Submit`, see that you get an error
5. Uncheck all `Type(s) of financial institution` boxes and hit `Submit`, see that you get an error

### No changes made, submission prevented
Screenshot 2024-03-22 at 2 27 02 PM

### Invalid TIN, RSSD ID, and no Type(s) selected
Screenshot 2024-03-26 at 1 45 57 PM

### Type - Other selected but not described
Screenshot 2024-03-22 at 2 28 48 PM
Screenshot 2024-03-22 at 2 28 56 PM

### CODE REVIEW

**Review by billhimmelsbach — COMMENTED** [review]
Heyo! I answered some of these questions over on the SBL Frontend channel (thanks for posting there!). Let's address those things, and then merge this in. We can address anything else if we have time before MVP. 👍

**Comment by meissadia** [comment]
@billhimmelsbach Screenshots updated.  Latest changes:
- Updated messaging for RSSD ID and Tax ID
- Disabled the `Other` textbox when the checkbox is not ticked
- Added error message to the `Type of financial institution` section when message is triggered
- Updated `Type of financial institution` header to remove the `(s)`

**Comment by meissadia** [comment]
I would like to refactor this form to use Context and avoid prop drilling of the `react-hook-form` properties, but that can be a post-MVP task.

**Comment by meissadia** [comment]
@natalia-fitzgerald @billhimmelsbach Just noticed that the intro text for `Update your financial institution identifying information` indicates that an Institution may not have an RSSD ID, so making that field required in this form could be problematic for those Institutions.

"If your financial institution does not have an RSSD ID, provide your TIN."

Screenshot 2024-03-26 at 3 23 11 PM

**Comment by billhimmelsbach** [comment]
Yeah, RSSD ID is not required. Not everyone is registered with NIC.

**Comment by meissadia** [comment]
Made RSSD ID optional 👍🏾

**Review by billhimmelsbach — COMMENTED** [review]
This is super great Meissa! The name is also optional, because a user might not have affiliates at all:

Screenshot 2024-03-28 at 12 03 58 PM

**Review by billhimmelsbach — APPROVED** [review]
On second thought, let's handle the affiliate name in your [later PR](https://github.com/cfpb/sbl-frontend/pull/325) to make things easier. I really appreciate the tests and the comments for Typescript weirdness. 👍

**Pull request merged**
