### PR TITLE
[Institution profile] Page-level error for API issues

### LINKED ISSUE #1030: [View Institution profile] Page level error alerts
- Error alert
  - If any data fetching fails, display a page-level error alert
  - If any data parsing fails, display a page-level error alert:
    - Error boundary around that piece? (Maybe new PR?)
    - Throw `500` for now?
  - Remove conditional render based on errors

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1030 

## Changes

- Render page-level error alert for API errors, as opposed to rendering a separate `500` page

## How to test this PR

1. Block API requests from the following source in Chrome dev tools:
    1. `localhost:8881/v1/institutions/123456789TESTBANK123`
2. Visit http://localhost:8899/institution/123456789TESTBANK123
3. Observe that things reflect the screenshot below.

## Screenshots

Screenshot 2024-11-07 at 3 05 43 PM

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Can we update this error to show this? 
Screenshot 2024-11-06 at 10 58 46 AM

**Comment by meissadia** [comment]
@natalia-fitzgerald Implementation updated to match you mockup. Screenshot updated above.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
The screenshot looks good - just need to add the underline to the link.

**Review by natalia-fitzgerald — APPROVED** [review]
@meissadia 
The only small change I have is to add the underline to the link. Looks good!

**Comment by meissadia** [comment]
Updated to address missing underline for email link.  Screenshot updated to show latest state.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
Would this same message show up on the Update your financial institution profile page when there are API errors?

**Comment by meissadia** [comment]
> @meissadia Would this same message show up on the Update your financial institution profile page when there are API errors?

@natalia-fitzgerald 
No, page-level alert has not yet been implemented there.  Opened the following ticket to ensure language updates and alerts are applied to the `Update institution profile` page: https://github.com/cfpb/sbl-frontend/issues/1054

**Pull request merged**
