### PR TITLE
[Filing] Upload - Adjust when we render the 'Unable to continue' messaging

### LINKED ISSUE #766: [Upload] Only show one status Alert
Image

### PR DESCRIPTION
**Pull request by meissadia**
Close #766

## Changes
- Moves the error Alert re: not being ready to save and continue down to the bottom of the page
  - Shows/hides this alert as demonstrated below

### Scenario 1 - New upload

https://github.com/cfpb/sbl-frontend/assets/2592907/a48cb02f-3a33-4680-a264-bb14c14de17f

### Scenario 2 - Existing upload

https://github.com/cfpb/sbl-frontend/assets/2592907/6b50e116-a047-494d-b788-fd2fbb7c267b

### Scenario 3 - Error uploading

https://github.com/cfpb/sbl-frontend/assets/2592907/15bb2bd4-2e0a-4f3b-ac62-6fbeea99d726

### Scenario 4 - Ready to save and continue

https://github.com/cfpb/sbl-frontend/assets/2592907/69908096-dba6-4381-8505-61e4e170aa74

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
- The error alert message for any time a user clicks the "Save and continue" button without completing the requirements for the step should be: "File upload and validation checks must be completed to save and continue."
- This error alert should be positioned at the bottom of the page under "Go back" and "Save and continue"
- In the example you show [here](https://github.com/cfpb/sbl-frontend/pull/767#issue-2373471935) the changes to the implementation would be to update the error alert text and move the error alert box to the bottom of the page as shown in the mock-up.

**Comment by meissadia** [comment]
@natalia-fitzgerald Updated demo videos to show current functionality.

**Comment by billhimmelsbach** [comment]
Hey @natalia-fitzgerald, mind taking a look at these changes in the videos above / on the preview site?

**Comment by natalia-fitzgerald** [comment]
@meissadia 
As a part of this PR will you add the alert to the Resolve errors and Review warnings pages? In order to create consistency across the alerts on all of these pages can you change the text to paragraph (instead of H4) and include a period? This is what we do on Resolve errors and Review warnings for this alert.

**Comment by natalia-fitzgerald** [comment]
@shindigira 
For now let's keep the form-level alert (it's an anomaly and field-level could make more sense but we're doing form-level for visual prominence and because it does apply to the whole form). The styling should be standard paragraph style with a period at the end of the sentence. 

- Regular weight (400)
- 16px
- Avenir Next

**Review by ojbravo — APPROVED** [review]
LGTM!

**Pull request merged**
