### PR TITLE
Nginx CSP Update

### PR DESCRIPTION
**Pull request by ojbravo**
Added GA code to index.html. Replaced 'unsafe-inline' in nginx.conf with nonce and white-listed https://dap.digitalgov.gov

### CODE REVIEW

**Review by billhimmelsbach — APPROVED** [review]
Heyo! This works super great Omar! This set up will fail currently though do to the hardened nginx image, but when you update with `main` to get some of the security changes we merged last night, it'll work great!
Screenshot 2024-06-21 at 5 18 53 AM

This will be a huge time saver if we end up needing this for approval, and I really appreciate your work making this ready to go! Thanks @ojbravo! 👍

**Comment by billhimmelsbach** [comment]
Looks great @ojbravo! We really appreciate your work on this!
launch

**Comment by jcadam14** [comment]
image

**Comment by lchen-2101** [comment]
cat_launch

**Comment by gduncklee** [comment]
ezgif com-webp-to-gif-converter

**Comment by meissadia** [comment]
SEND IT!
launch-ezgif com-webp-to-gif-converter

**Comment by hkeeler** [comment]
image

**Comment by hkeeler** [comment]
image

**Review by billhimmelsbach — APPROVED** [review]
🚀 Thanks for your awesome work, and welcome to the team @ojbravo! 🚀

**Comment by guffee23** [comment]
https://media.giphy.com/media/CqJW7tiToflSUPokAR/giphy.gif?cid=790b76115move04e224zn8ieefhjkj79v5ct1utbdwlwm6ay&ep=v1_gifs_search&rid=giphy.gif&ct=g

**Comment by nargis-sultani** [comment]
giphy-ezgif com-webp-to-gif-converter

**Pull request merged**
