### PR TITLE
[Design review] Update financial institution profile

### LINKED ISSUE #309: [Design review] Update institution profile
- [x] Sections
  - (all intro Paragraphs) should be 670px wide
  - Use SectionIntro component
  - ex. "Review your financial details" needs it
- [x] Breadcrumb
  - Items should mirror page titles
    - ex. View you financial institution profile
- [ ] [Section] Update your financial...identifying
  - [ ] Define TIN on first use in paragraph
  - [x] Use SectionIntro component
- [x] Review and update all page copy
  - Lead paragraph should say "complete form" instead of "fill out form"
- [x] Heading spacing
  - Heading4 - margin-bottom should be 15px?
- [ ] Type of financial institution
  - [x] Clear other text input when box is unchecked
  - [ ] Validation: Ensure comma separated
- [x] Update your financial institution affiliate information
  - 15px -> 30px between fields
- [x] Additional details
  - Remove placeholder text
- [x] Page 
  - bottom margin: 60px (always)

### PR DESCRIPTION
**Pull request by meissadia**
Closes #309 

## Changes
- Update page copy based on design files
- Update spacing between grouped fields (30px)
- Update breadcrumb labels to match target page titles
- Fix section introduction width (670px via SectionIntro component)
- Update ViewFinancialProfile page structure to match UpdateFinancialProfile to avoid content shift when navigating between them

## Questions
- Re: Define acronyms on first use
  - Does this only apply to the first use on the page? 
  - Or each first use in each section?
- Type of financial institution (other) - Validation (comma separated list)
  - How would we determine what should/shouldn't be considered multiple types?
  - Are there any characters that are no allowed?

## Screenshots
screencapture-localhost-8899-institution-123456789TESTBANK123-update-2024-03-26-16_37_52

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I made some comments in the Figma file but I'll try to capture them here: 
- Change "contact our support staff" to "email our support staff" 
- Change text under "Update your financial institution identifying information" to what's in the Figma file. 
- Change RSSD ID to optional 
- Change "Research, Statistics, Supervision, Discount (RSSD) ID to Research, Statistics, Supervision, Discount Identifier (RSSD ID) - all instances
- Change text input for "Other" to disabled unless "Other" is selected
- Change parent entity name and top holder name to optional and label with "(optional)"

For acronyms our standard practice is to spell the acronym out on first mention on a page.

**Comment by billhimmelsbach** [comment]
> Change "contact our support staff" to "email our support staff" (in all instances - form and success message)

Can we do this across the app in a separate PR? I'd rather not do it piecemeal, and instead change it across all the pages at once.

**Comment by billhimmelsbach** [comment]
Also, let's keep this PR contained to only the "Update your financial institution profile" and not include "View your financial institution profile" changes in this PR.

**Comment by billhimmelsbach** [comment]
> > Change "contact our support staff" to "email our support staff" (in all instances - form and success message)
> 
> Can we do this one across the app in a separate PR? I'd rather not do it piecemeal, and instead change it across all the pages at once.

Here's that PR by the way:
https://github.com/cfpb/sbl-frontend/pull/330

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I left comments in Figma for all of these items:
- Match body text from Figma file under "Review your financial institution details"
- Match the body text from Figma file under "Update your financial institution identifying information"
- Space above body text that is above "Type of financial institution" well should be 45px
- Disable submit button until a user makes changes to the form. This prevents a user from submitting without changes.
  - If we need placeholder text for the warning box in the meantime: 
"You did not make a change to your financial institution profile data. No update request has been sent to our support staff."

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@meissadia - This is getting close. I do have a few edits. 
I left comments in Figma for all of these items:
- Match body text from Figma file under "Review your financial institution details"
- Match the body text from Figma file under "Update your financial institution identifying information"
- Space above body text that is above "Type of financial institution" well should be 45px
- Disable submit button until a user makes changes to the form. This prevents a user from submitting without changes.
  - If we need placeholder text for the warning box in the meantime: 
"You did not make a change to your financial institution profile data. No update request has been sent to our support staff."

**Comment by meissadia** [comment]
Updates 3/29/2024
- [Fix][Update institution] Update copy - Identifying information
- Change related to `Review your financial institution details` section intro made in subsequent [PR #327](https://github.com/cfpb/sbl-frontend/pull/327/files#diff-1820633033cd08810341f25f339c8f97cd17fa5b00b8a67637e6286d66b3724f)

**Review by natalia-fitzgerald — APPROVED** [review]
@meissadia - Thanks for your work on this. Looks great!

**Review by billhimmelsbach — APPROVED** [review]
Code looks good too! 👍

**Pull request merged**
