### PR TITLE
[View Institution Profile] Language updates

### LINKED ISSUE #1013: [View Institution profile] Update language
Institution profile: http://localhost:8899/institution/123456789TESTBANK123

- Language
  - Most unpopulated fields: "Not available" => "Not applicable"
  - Refer to [table](https://github.com/cfpb/sbl-ux/issues/2) for which unpopulated fields should be shown as blank
- Add warning alert for the "Not provided" fields
    Image

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1013 

## Completed Changes

- Updated the fallback values for most fields to "Not applicable"
- Ensured `Type of Financial Institution`, `Federal Taxpayer Identification Number (TIN)` show as "Not provided" when missing
- Updated language for `LEI Status` from "Active/Inactive" to "Issued/Lapsed"
- Display alert for `Type of Financial Institution`, `Federal Taxpayer Identification Number (TIN)`, or `LEI Status` when missing/lapsed.

### Language updates
```
    const testBlankValues = {
      lei: 'FI_LEI',
      name: 'FI_INSTITUTION_NAME',
      hq_address_street_1: 'HQ_ADDRESS_STREET_1',
      hq_address_city: 'HQ_ADDRESS_CITY',
      hq_address_state: 'HQ_ADDRESS_STATE',
      hq_address_state_code: 'HQ_ADDRESS_STATE_CODE',
      hq_address_zip: 'HQ_ADDRESS_ZIP',
    };
```

1. [ViewInstitutionProfile > index.tsx] Replace the `data` param highlighted in the screenshot below with the following.
    Screenshot 2024-10-22 at 2 03 45 PM

2. Visit the Institution profile page
    - ex. http://localhost:8899/institution/123456789TESTBANK123
3. Confirm fields display the correct fallback value (blank or "Not applicable").

### Language updates 
- Fields marked as `Always populated` in the reference table are populated with their fieldname (i.e FI_INSTITUTION_NAME)
- Field that were previously "blank" are displayed as "Not populated" (TIN, Types of Financial Institution).
- Others are populated with the appropriate fallback value.  
<br/>

screencapture-localhost-8899-institution-123456789TESTBANK123-2024-11-01-10_20_28

### CODE REVIEW

**Review by tanner-ricks — DISMISSED** [review]
Looks fine from my end. Don't know if Natalia needs to check this out or not though.

**Comment by meissadia** [comment]
@natalia-fitzgerald I've updated this PR to switch `blank` fields to display as "Not provided".  The screenshot above reflects these changes.

**Comment by meissadia** [comment]
@natalia-fitzgerald Added the warning alert when missing TIN or Type of FI.  Screenshot above has been updated. 
 
I notice the spacing between `!` icon and the text in my implementation compared to your reference image differs (less in my implementation).  Wondering if this is a one-off issue we should address in the SBL Frontend or if this is an issue with the DSR's [Alert (field-level)](https://cfpb.github.io/design-system-react/?path=/story/components-draft-alerts--warning-field-level) component.

**Comment by meissadia** [comment]
@natalia-fitzgerald Also updated to include the alert for `Lapsed` LEIs.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
This is looking good. 

For "Type of financial institution" can you update the text to: You must provide your type of financial institution to file. Visit update your financial institution profile to provide this information.

**Review by natalia-fitzgerald — CHANGES_REQUESTED** [review]
@meissadia 
This is looking good. 

For "Type of financial institution" can you update the text to: 
You must provide your type of financial institution to file. Visit update your financial institution profile to provide this information.

---

I also noticed the spacing/alignment issue between ! icon and the text. I seem to recall us flagging this as a problem with the DSR's field level alert. I'd have to look through my notes.  

Here's how the DSR's field level alert looks: 
- Space between icon and text is tight and text appears to sit on the baseline of the icon (rather than centered)
Screenshot 2024-10-31 at 9 00 52 PM

This might be the PR where we explored fixing this (almost a year ago):
https://github.com/cfpb/design-system-react/pull/278

**Comment by meissadia** [comment]
@natalia-fitzgerald Alert message for `Type of financial institution` has been updated.  Screenshot updated. 

Based on the referenced PR about Alert spacing, sounds like a "later" item, so I'll leave it alone for now.

**Review by natalia-fitzgerald — APPROVED** [review]
@meissadia 
This looks good. 

My only remaining question is whether email domain should be "not available." My understanding is that we would always have email domain unless the entire system is down in some way?

**Review by billhimmelsbach — APPROVED** [review]
Looks good @meissadia!

**Pull request merged**
