### PR TITLE
[Snapshot testing - Part 3] Shared lending platform

### LINKED ISSUE #1062: [e2e] Add snapshot testing
https://playwright.dev/docs/test-snapshots

Goals
- Make it easy to identify visual changes to SBL Frontend pages
- Do not interfere with the execution of existing e2e tests

Tasks
- [x] Get a single snapshot test working
- [x] Add a configuration option to run snapshot tests separately
- [x] Add snapshot tests for each page
- [ ] Fine tune snapshot settings to minimize flakiness 
- [x] Generate all `baseline` snapshot images

PRs
- [x]  #1070 
- [ ] https://github.com/cfpb/sbl-frontend/pull/1072
- [ ] https://github.com/cfpb/sbl-frontend/pull/1087

### LINKED ISSUE #1090: [e2e] Snapshot testing - Add script to easily update baseline snapshots
I've struggled to update snapshots via the `--update-snapshots` flag, instead having to
- delete the previously generated snapshots 
- re-run e2e tests to generate new snapshots
- re-run e2e tests to validate new snapshots
  
Need to determine how to easily re-generate snapshots via command line.

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1062
Closes #1090 

## Changes
This PR builds off of https://github.com/cfpb/sbl-frontend/pull/1072, so includes all of those commits, but is separate to emphasize this PR's focus on adding snapshots to the `shared-lending-platform`  tests.   Once #1072 is reviewed and merged, this PR should be much easier to review.

- Add snapshot checks to E2E Shared Lending Platform tests

## How to test this PR
1. `yarn test:e2e:snapshot`
2. Run `shared-filing-platform` tests

## Screenshots
Screenshot 2024-12-12 at 10 19 08 AM

### CODE REVIEW

**Review by billhimmelsbach — COMMENTED** [review]
Looking great and thanks for remembering to add the documentation to the readme.

I did notice the flakiness you mentioned when it comes to the footer: just like you said the gray on black with the link dots cause the most issues.

My thought on it: could we have one assertion for the unauthenticated landing page that does the image diff on the full page and the footer, then mask the footer with a mask for the rest of the tests since the footer is static? 

You could add a bool that's like `isFlakyRegionIgnored` or just `isFooterIgnored` to your [takeSnapshot](https://github.com/cfpb/sbl-frontend/blob/1062-snapshot__shared-lending-platform/e2e/utils/snapshotTesting.ts#L9) function that defaults to true. Then for your one test on the unauthenticated landing page that includes the full page and footer, you could set `isFlakyRegionIgnored=false`. Then for the rest of the tests, `isFlakyRegionIgnored` could default to true, and a mask could be applied to another class like `.snapshot-ignore-flaky` or you could just pick out the footer class that already exists and mask that.

I think it would cut down a lot on the flakiness hopefully, since then we won't be testing the footer over and over. 🤞

**Comment by meissadia** [comment]
I've got a draft to mask the Footer on most pages but will wait until we merge https://github.com/cfpb/sbl-frontend/pull/1072 to cut down on merge conflicts.

**Comment by billhimmelsbach** [comment]
There is the option in playwright just to [take a screenshot of an element](https://playwright.dev/docs/screenshots#element-screenshot), so you could just take a screenshot of the footer if you wanted to. I'm not sure though if that would make the test more/less flaky @meissadia, but might be worth testing?

**Review by billhimmelsbach — APPROVED** [review]
Great! Thanks for ticketing that.

**Pull request merged**
