### PR TITLE
[Institution profile pages] Crumb trail spacing

### LINKED ISSUE #337: [CrumbTrail] Should be 30px from the rule line
Site Header
`<30px>`
CrumbTrail
`<30px>`
...the rest

### PR DESCRIPTION
**Pull request by meissadia**
Closes #337

## Changes

- CrumbTrail - Support independent rendering
- [[FormWrapper] Support removing top margin](https://github.com/cfpb/sbl-frontend/commit/af0b2d17c38a959c5133d237d2e4cca16663f05b)
- [[Page][View institution] Refactor to render correct CrumbTrail spacing](https://github.com/cfpb/sbl-frontend/commit/f318e221aacc1c31aeb04311c358784fa69875aa)
- [[Page][Update institution] Refactor to render correct CrumbTrail spacing](https://github.com/cfpb/sbl-frontend/commit/d9caa2bb00c1bcea19a70c1cc58c4861ebd7c8dc)
- [Page][Summary] Update CrumbTrail spacing

## How to test this PR

1. Visit http://localhost:8899/institution/123456789TESTBANK123/update
2. Verify CrumbTrail is 30px from site header
3. Visit http://localhost:8899/institution/123456789TESTBANK123
4. Verify CrumbTrail is 30px from site header

## Screenshots
View institution profile
Screenshot 2024-03-28 at 5 31 29 PM

Update institution profile

Screenshot 2024-03-28 at 5 31 16 PM

Summary

Screenshot 2024-04-01 at 10 11 49 AM

### CODE REVIEW

**Review by billhimmelsbach — CHANGES_REQUESTED** [review]
Overall, this looks great! Just one issue on the Summary page after submitting "Update your financial institution profile," it looks like the crumbtrail is still 45px instead of 30px. 

Screenshot 2024-04-01 at 7 43 31 AM

After this is merged, @shindigira can make the same change for the Complete your user profile (with no email domain associations). 👍

**Comment by billhimmelsbach** [comment]
> > Overall, this looks great! Just one issue on the Summary page after submitting "Update your financial institution profile," it looks like the crumbtrail is still 45px instead of 30px.
> > Screenshot 2024-04-01 at 7 43 31 AM
> > After this is merged, @shindigira can make the same change for the Complete your user profile (with no email domain associations). 👍
> 
> @meissadia @billhimmelsbach I corrected the issue on the Summary page in my [PR - Summary](https://github.com/cfpb/sbl-frontend/pull/311/files#diff-8824e3fd82564968318ec496ce8be63c94a94a4e749ca0729320c831072f79d0) as well as the other forms not included

Ok! Please make a note on your PR that this Summary page and the rest of the other forms will be part of your design review as well? @natalia-fitzgerald will be looking at those pages later today. 👍

**Comment by meissadia** [comment]
Sorry, was already in progress after standup. Updated /summary CrumbTrail spacing

Screenshot 2024-04-01 at 10 11 49 AM

**Review by billhimmelsbach — DISMISSED** [review]
Looks good! Thanks @meissadia!

**Pull request merged**
