### PR TITLE
styles: [Filing landing] Underline Institution links

### LINKED ISSUE #603: [Filing home] Underline Institution links

### PR DESCRIPTION
**Pull request by meissadia**
Close #603

## Changes
- Use the `<ListLink>` component for list items
- Structure the `ListLink` content so that borders are appropriately applied at different breakpoints

## Screenshots
|Page|Desktop|Mobile|
|---|---|---|
|FilingHome|review-desktop|review-mobile|
|User Profile|profile-associated-desktop|profile-associated-mobile|

### CODE REVIEW

**Comment by natalia-fitzgerald** [comment]
@meissadia 

I explored the design of this component to see if we could simplify it and bring it into closer alignment with a standard CFPB DS component. I am seeing a lot of complications in the merging of link text and non-link text for content that is quite variable in length -- and trying to get this to look seamless between desktop and mobile. 

I explored removing the word "Approved" and including the checkmark icon within the link. The concept of "Approved" originally came out of the idea that some institutions would be in an approved state and others would be in a pending state. And, these state would be communicated visually to the user. Now that we are not presenting the financial institutions that are pending, the word "Approved" is not essential. Additionally we don't mention the concept of "Approval" in the body content. We refer to this as "associated."

### Associated financial institution (single)
|Desktop|Mobile|
|---|---|
|Screenshot 2024-05-30 at 7 44 59 AM|Screenshot 2024-05-30 at 7 45 05 AM|


### Associated financial institutions (multiple)
|Desktop|Mobile|
|---|---|
|Screenshot 2024-05-30 at 7 45 16 AM|Screenshot 2024-05-30 at 7 45 26 AM|

**Comment by dan-padgett** [comment]
If we're only showing institutions that have been successfully associated with the user's profile, I think we could get rid of the check mark to simplify things even further. Also, if the icon isn't interactive, removing it also eliminates the risk that a user clicks on it expecting that it do the same thing as the link.

**Comment by meissadia** [comment]
@natalia-fitzgerald @dan-padgett 

Because of the current composition (icon separate from the link) I'm struggling to get the borders for a visited link on mobile to reflect the color change. Should the shared borders on mobile reflect the `visited` state of links? 
 
Also haven't gotten the icon color for visited links to match.  Eliminating the icon would eliminate a number of friction points. 

### Associated financial institution (single)
|Desktop|Mobile|
|---|---|
|Screenshot 2024-05-30 at 2 07 44 PM|Screenshot 2024-05-30 at 2 07 30 PM|

### Associated financial institutions (multiple)


|Desktop|Mobile|
|---|---|
|Screenshot 2024-05-30 at 2 04 36 PM|Screenshot 2024-05-30 at 2 04 46 PM|

### View your user profile
Screenshot 2024-05-30 at 2 08 31 PM

**Comment by natalia-fitzgerald** [comment]
@meissadia - Are we using the list link styling for this? Is the icon not inside of the link? In the list link component in the DS an icon is included. It is on the right side but would we be able to use that component and move the icon to the left?

**Comment by meissadia** [comment]
@natalia-fitzgerald Thank you for connecting the dots back to the DS component.  I've updated our implementation to match the DS Link list structure and things are looking good 👍🏾

**Review by billhimmelsbach — APPROVED** [review]
This looks great! 🎉

Screenshot 2024-05-31 at 3 50 53 PM

**Pull request merged**
